source 'https://rubygems.org'
gem 'rails', '3.2.1'
gem 'sqlite3'
group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'
  gem 'uglifier', '>= 1.0.3'
end
gem 'jquery-rails'
gem "devise", ">= 2.1.0"
gem "devise_invitable", ">= 1.0.1"
gem "cancan", ">= 1.6.7"
gem "rolify", ">= 3.1.0"
gem "bootstrap-sass", ">= 2.0.3"
gem "simple_form"
gem "will_paginate", ">= 3.0.3"
gem 'jquery-tablesorter'